name: Create release
on:
  push:
    tags:
      - 'v*.*.*'
permissions:
  contents: write


jobs:       
  upload_artifacts:
    uses: ./.github/workflows/upload_artifacts.yml

  
  create_release:
    needs: upload_artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./publish

      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./publish/*/*"
          generateReleaseNotes: true
          makeLatest: true