name: 'Build - publish windows'
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

jobs:
  build:
    runs-on: "windows-latest"
    steps:
      - name: Setup timezone
      # You may pin to the exact commit or the version.
      # uses: zcong1993/setup-timezone@7215c3ec086d387e4618c4b81482d06d998c90a9
        uses: zcong1993/setup-timezone@v1.1.2
        with:
          # which timezone you want to use
          timezone: Asia/Shanghai # default is UTC
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x). Early access versions can be specified in the form of e.g. 14-ea, 14.0.0-ea, or 14.0.0-ea.28
          java-version: '11'
          #distrubution: 'temurin'
          distribution: 'temurin'
          cache: gradle
    # The package type (jre, jdk, jdk+fx)
          java-package: 'jdk+fx' # optional, default is jdk
      - name: use Written shell script
        run: "bash ./CI/publish_windows.sh"
      - name: path may wrong
        run: 'cd FanControl && bash ../CI/publish_windows.sh'
      - name: tree there
        run: 'tree . --depth 3'
